### ISSUE TITLE
mPresenter ,mView = null in onActivityResult

### ISSUE THREAD

**Issue by TieuNhi95** [benoitletondor/Android-Studio-MVP-template#15]
thanks for your template
but i have a problem with mPresenter and mView 
sometime ,its return null in onActivityResult.

**Comment by benoitletondor** [comment]
Hi @TieuNhi95 ,

Yes, it's unfortunate but your `Activity` is not started when reaching `onActivityResult`, meaning that your `mView` variable will be null into your `Presenter`.

You should always ensure you handle those cases with something like that : 

```
public class MyPresenter extends BasePresenterImpl {
     @Nullable
     private Stuff mTempResult;

     @Override
     public void onStart(boolean viewCreated) {
          // ... Your usual code here

          if( mTempResult != null ) {
               // Handle your result
               mTempResult = null;
          }
     }

     public void onOtherActivityResult(@NonNull Stuff result) {
           if( mView != null ) {
                 // Handle your result directly here
           } else {
                 mTempResult = result;
           }
     }
}
```

This way you ensure that your result will be handled either right away if the view is available, or at the next start otherwise.

Let me know if it's unclear.

**Comment by TieuNhi95** [comment]
thanks, i got it (y)
